---
output: github_document
---

# Download contacy surveys for use in infectious disease modelling in R

<!-- badges: start -->
<!-- badges: end -->

`contactsurveys` is an `R` package to download contacy survey data, which can be used to derive social mixing matrices, see for example [socialmixr](https://github.com/epiforecasts/socialmixr).

# Installation

The package can be installed using

The current development version can be installed using the `remotes` package

```r
remotes::install_github("njtierney/contactsurveys")
```

# Documentation

For information on how to use the contactsurveys package, see the [introduction vignette](TODO).

## Contributors



<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->

All contributions to this project are gratefully acknowledged using the [`allcontributors` package](https://github.com/ropensci/allcontributors) following the [allcontributors](https://allcontributors.org) specification. Contributions of any kind are welcome!

### Code


<a href="https://github.com/epiforecasts/socialmixr/commits?author=sbfnk">sbfnk</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=Bisaloo">Bisaloo</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=lwillem">lwillem</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=alxsrobert">alxsrobert</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=Degoot-AM">Degoot-AM</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=pearsonca">pearsonca</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=jarvisc1">jarvisc1</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=jamesmbaazam">jamesmbaazam</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=mariabnd">mariabnd</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=samclifford">samclifford</a>, 
<a href="https://github.com/epiforecasts/socialmixr/commits?author=TimTaylor">TimTaylor</a>



### Issue Authors


<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Abastistician">bastistician</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3ABlackEdder">BlackEdder</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3APinzo1">Pinzo1</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Aflorpi">florpi</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Acchauve">cchauve</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Athutran">thutran</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Adlaydon">dlaydon</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Adeusthindwa">deusthindwa</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Akrivit">krivit</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Alinyang17">linyang17</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Acliu822">cliu822</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3ANaomiWaterlow">NaomiWaterlow</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Aaakhmetz">aakhmetz</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Aadamkucharski">adamkucharski</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3Achitrams">chitrams</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+author%3AIsaacStopard">IsaacStopard</a>



### Issue Contributors


<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+commenter%3Avikkytom">vikkytom</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+commenter%3Anjtierney">njtierney</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+commenter%3Abahadzie">bahadzie</a>, 
<a href="https://github.com/epiforecasts/socialmixr/issues?q=is%3Aissue+commenter%3Ajoshwlambert">joshwlambert</a>


<!-- markdownlint-enable -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->




