# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ":=", # <clean.contact_survey>
  "country", # <clean.contact_survey>
  "..age.unit", # <clean.contact_survey>
  "..high", # <clean.contact_survey>
  "..low", # <clean.contact_survey>
  ":=", # <.list_surveys>
  "common_doi", # <.list_surveys>
  "doi.nb", # <.list_surveys>
  "identifier.1", # <.list_surveys>
  ".SD", # <.list_surveys>
  "title", # <.list_surveys>
  "creator", # <.list_surveys>
  "identifier.2", # <.list_surveys>
  ":=", # <load_survey>
  "..main_id", # <load_survey>
  ".N", # <load_survey>
  "..merge_id", # <load_survey>
  NULL
))
