# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ":=", # <download_survey>
  "file_name", # <download_survey>
  ":=", # <.list_surveys>
  "common_doi", # <.list_surveys>
  "doi.nb", # <.list_surveys>
  "identifier.1", # <.list_surveys>
  ".SD", # <.list_surveys>
  "title", # <.list_surveys>
  "creator", # <.list_surveys>
  "identifier.2", # <.list_surveys>
  NULL
))
