# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ":=", # <list_surveys>
  "common_doi", # <list_surveys>
  "doi.nb", # <list_surveys>
  "identifier.1", # <list_surveys>
  ".SD", # <list_surveys>
  "title", # <list_surveys>
  "creator", # <list_surveys>
  "identifier.2", # <list_surveys>
  NULL
))
